import LegalPage from "@/components/LegalPage";
export default function Privacy(){return <LegalPage kicker="Confidențialitate" title="Cum sunt prelucrate și protejate datele" updated="14 iulie 2026" intro="Aplicăm minimizarea datelor: un calcul personal simplu nu necesită CNP, IBAN, adresă sau document medical." notice="Datele medicale și identificatorii naționali sunt date cu risc ridicat. Încărcarea lor nu trebuie activată până la configurarea criptării, retenției, DPA și evaluării de impact aplicabile." sections={[
{title:"1. Categorii de date",paragraphs:["Putem prelucra date de cont, profil salarial, program, calcule, plăți, securitate, audit și suport."],items:["email, nume și provider de autentificare","brut, sporuri, beneficii, pontaj, absențe și rezultate","firmă, roluri, angajați și istoric de modificări","date sensibile opționale numai când o funcție justifică prelucrarea"]},
{title:"2. Scopuri și temeiuri",paragraphs:["Datele susțin furnizarea serviciului, autentificarea, salvarea, facturarea, suportul și securitatea. Temeiul depinde de context: contract, obligație legală, interes legitim, consimțământ sau un temei specific pentru categorii speciale."]},
{title:"3. Furnizori",paragraphs:["Folosim furnizori pentru hosting, autentificare, baze de date, plăți și AI numai pentru modulele activate. Lista este publicată la Subprocesatori."]},
{title:"4. AI și minimizare",paragraphs:["CNP-ul, IBAN-ul, adresa și diagnosticul nu sunt trimise implicit furnizorului AI."]},
{title:"5. Drepturi",paragraphs:["Poți solicita acces, rectificare, ștergere, restricționare, portabilitate și opoziție, în limitele legii."]},
{title:"6. Contact",paragraphs:["Contact: helpcalculatorsalariu@gmail.com. Poți depune plângere la autoritatea de supraveghere competentă."]}
]} english={{kicker:"Privacy",title:"How data is processed and protected",updated:"14 July 2026",intro:"We apply data minimisation: a basic personal calculation does not require a national ID, IBAN, address or medical document.",notice:"Health data and national identifiers are high-risk data. Uploading them must not be enabled until encryption, retention, the DPA and any required impact assessment are configured.",sections:[
{title:"1. Data categories",paragraphs:["We may process account, payroll profile, schedule, calculation, payment, security, audit and support data."],items:["email, name and authentication provider","gross salary, bonuses, benefits, time records, absences and results","company, roles, employees and change history","optional sensitive data only where a feature justifies processing"]},
{title:"2. Purposes and legal bases",paragraphs:["Data supports service delivery, authentication, saving, billing, support and security. The legal basis depends on context: contract, legal obligation, legitimate interest, consent or a specific basis for special categories."]},
{title:"3. Providers",paragraphs:["We use providers for hosting, authentication, databases, payments and AI only for enabled modules. The list is published on the Subprocessors page."]},
{title:"4. AI and minimisation",paragraphs:["National IDs, IBANs, addresses and diagnoses are not sent to the AI provider by default."]},
{title:"5. Rights",paragraphs:["You may request access, correction, deletion, restriction, portability and objection within applicable legal limits."]},
{title:"6. Contact",paragraphs:["Contact: helpcalculatorsalariu@gmail.com. You may complain to the competent supervisory authority."]}
]}}/>}
