import LegalPage from "@/components/LegalPage";
export default function Terms(){return <LegalPage kicker="Termeni și condiții" title="Regulile de utilizare ale platformei Calculator Salariu" updated="14 iulie 2026" intro="Platforma oferă calcule, organizare și explicații. O simulare nu devine document oficial și trebuie verificată înainte de utilizare." notice="Textul trebuie revizuit de un avocat înainte de utilizarea comercială la scară largă, mai ales pentru D112, REGES și documente medicale." sections={[
{title:"1. Serviciul",paragraphs:["Platforma oferă estimări salariale, programe de lucru, profiluri, istoric, colaborare Business, plăți și funcții AI."]},
{title:"2. Conturi și securitate",paragraphs:["Utilizatorul protejează parola și activitatea contului. Administratorii unei firme trebuie să folosească propriile conturi, nu o parolă comună."],items:["email valid și verificat","roluri individuale","acces suspendabil la abuz sau risc de securitate"]},
{title:"3. Calcule",paragraphs:["Seturile fiscale sunt versionate. Valorile personalizate produc simulări personalizate, care trebuie verificate."]},
{title:"4. Credite și abonamente",paragraphs:["Primul calcul lunar complet este gratuit. Un credit deblochează o lună pentru un profil; recalculările aceleiași luni nu consumă alt credit. Abonamentele se reînnoiesc până la anulare."],items:["upgrade-ul păstrează datele","downgrade-ul poate necesita arhivarea angajaților peste limită","rambursările se analizează conform legii și consumului serviciului digital"]},
{title:"5. Firme",paragraphs:["Firma stabilește scopul și temeiul prelucrării datelor angajaților și acordă acces numai persoanelor autorizate."]},
{title:"6. AI și disponibilitate",paragraphs:["AI-ul nu salvează fără confirmare și nu trebuie folosit pentru decizii disciplinare sau juridice. Serviciul poate avea mentenanțe ori limitări ale furnizorilor."]},
{title:"7. Contact",paragraphs:["helpcalculatorsalariu@gmail.com"]}
]} english={{kicker:"Terms and Conditions",title:"Rules for using the Salary Calculator platform",updated:"14 July 2026",intro:"The platform provides calculations, organisation and explanations. A simulation is not an official document and must be verified before use.",notice:"This text requires legal review before large-scale commercial use, especially for D112, REGES and medical documents.",sections:[
{title:"1. Service",paragraphs:["The platform provides payroll estimates, work schedules, profiles, history, Business collaboration, payments and AI features."]},
{title:"2. Accounts and security",paragraphs:["Users protect their password and account activity. Company administrators must use individual accounts rather than a shared password."],items:["valid and verified email","individual roles","access may be suspended for abuse or security risk"]},
{title:"3. Calculations",paragraphs:["Fiscal rule sets are versioned. Custom values produce custom simulations that require verification."]},
{title:"4. Credits and subscriptions",paragraphs:["The first complete monthly calculation is free. One credit unlocks one month for one profile; recalculating the same month consumes no additional credit. Subscriptions renew until cancelled."],items:["upgrades keep existing data","downgrades may require archiving employees above the new limit","refunds are assessed under applicable law and digital service consumption"]},
{title:"5. Companies",paragraphs:["The company determines the purpose and legal basis for employee data and grants access only to authorised people."]},
{title:"6. AI and availability",paragraphs:["AI does not save without confirmation and must not be used for disciplinary or legal decisions. The service may have maintenance or provider limitations."]},
{title:"7. Contact",paragraphs:["helpcalculatorsalariu@gmail.com"]}
]}}/>}
