"use client";

import { useEffect, useState } from "react";
import { addDoc, collection, deleteDoc, doc, onSnapshot, orderBy, query, serverTimestamp, updateDoc } from "firebase/firestore";
import WorkspaceTabs from "@/components/WorkspaceTabs";
import { db } from "@/lib/firebase";
import { useCurrentUser } from "@/lib/use-current-user";
import { useUI } from "@/lib/ui-context";

type Profile={id:string;name:string;jobTitle?:string;grossSalary?:number;workMode?:string;active?:boolean};
export default function ProfilesPage(){const{language}=useUI();const ro=language==="ro";const{user,loading}=useCurrentUser();const[profiles,setProfiles]=useState<Profile[]>([]);const[name,setName]=useState("");const[gross,setGross]=useState(6000);const[mode,setMode]=useState("standard");const[saving,setSaving]=useState(false);
 useEffect(()=>{if(!user)return;return onSnapshot(query(collection(db,"users",user.uid,"profiles"),orderBy("createdAt","asc")),snap=>setProfiles(snap.docs.map(d=>({id:d.id,...d.data()} as Profile))))},[user]);
 async function add(){if(!user||!name.trim())return;setSaving(true);try{await addDoc(collection(db,"users",user.uid,"profiles"),{name:name.trim(),grossSalary:gross,workMode:mode,active:true,createdAt:serverTimestamp(),updatedAt:serverTimestamp()});setName("")}finally{setSaving(false)}}
 if(loading)return <main className="platform-page">...</main>;if(!user)return <main className="platform-page"><section className="platform-hero"><h1 className="platform-title">{ro?"Autentificare necesară":"Sign-in required"}</h1></section></main>;
 return <main className="platform-page"><WorkspaceTabs/><section className="platform-hero"><span className="platform-kicker">{ro?"Profiluri personale":"Personal profiles"}</span><h1 className="platform-title">{ro?"Păstrează separat fiecare configurație salarială.":"Keep each payroll configuration separate."}</h1><p className="platform-subtitle">{ro?"Un profil reține salariul, programul, sporurile și regulile curente. Fiecare lună salvată rămâne un instantaneu și nu se schimbă când editezi profilul.":"A profile stores current salary, schedule, bonuses and rules. Every saved month remains a snapshot and does not change when the profile is edited."}</p></section><section className="platform-grid"><article className="platform-card span-5"><h2>{ro?"Adaugă profil":"Add profile"}</h2><div style={{display:"grid",gap:12}}><label>{ro?"Denumire":"Name"}<input className="auth-input" value={name} onChange={e=>setName(e.target.value)} placeholder={ro?"Ex: Eu – loc principal":"e.g. Main job"}/></label><label>{ro?"Salariu brut":"Gross salary"}<input className="auth-input" type="number" value={gross} onChange={e=>setGross(Number(e.target.value))}/></label><label>{ro?"Program":"Schedule"}<select className="auth-input" value={mode} onChange={e=>setMode(e.target.value)}><option value="standard">{ro?"Normal":"Standard"}</option><option value="parttime">Part-time</option><option value="shifts">{ro?"Ture":"Shifts"}</option><option value="custom">{ro?"Personalizat":"Custom"}</option></select></label><button className="platform-button" disabled={saving} onClick={add}>{saving?(ro?"Se salvează...":"Saving..."):(ro?"Adaugă profil":"Add profile")}</button></div></article><article className="platform-card span-7"><h2>{ro?"Profilurile tale":"Your profiles"}</h2>{profiles.length===0?<p>{ro?"Nu ai încă profiluri salvate.":"You have no saved profiles yet."}</p>:<div style={{display:"grid",gap:10}}>{profiles.map(profile=><div key={profile.id} style={{display:"grid",gridTemplateColumns:"1fr auto",gap:12,alignItems:"center",padding:14,border:"1px solid var(--line-ui)",borderRadius:16,background:"var(--surface-raised)"}}><div><strong>{profile.name}</strong><div style={{color:"var(--text-muted)",fontSize:12,marginTop:4}}>{profile.grossSalary?.toFixed(2)} lei · {profile.workMode}</div></div><div style={{display:"flex",gap:8}}><button className="platform-button secondary" onClick={()=>updateDoc(doc(db,"users",user.uid,"profiles",profile.id),{active:!profile.active,updatedAt:serverTimestamp()})}>{profile.active===false?(ro?"Activează":"Activate"):(ro?"Arhivează":"Archive")}</button><button className="platform-button secondary" onClick={()=>deleteDoc(doc(db,"users",user.uid,"profiles",profile.id))}>{ro?"Șterge":"Delete"}</button></div></div>)}</div>}</article></section></main>}
