"use client";

import { useEffect,useMemo,useState } from "react";
import { addDoc,collection,doc,getDoc,onSnapshot,orderBy,query,serverTimestamp,updateDoc } from "firebase/firestore";
import WorkspaceTabs from "@/components/WorkspaceTabs";
import { db } from "@/lib/firebase";
import { useCurrentUser } from "@/lib/use-current-user";
import { useUI } from "@/lib/ui-context";

type Employee={id:string;displayName:string;employeeCode?:string;department?:string;jobTitle?:string;grossSalary?:number;workMode?:string;active?:boolean};
type Org={id:string;employeeLimit?:number;activeEmployees?:number;name?:string};
export default function EmployeesPage(){const{language}=useUI();const ro=language==="ro";const{user,loading}=useCurrentUser();const[org,setOrg]=useState<Org|null>(null);const[employees,setEmployees]=useState<Employee[]>([]);const[name,setName]=useState("");const[code,setCode]=useState("");const[department,setDepartment]=useState("");const[gross,setGross]=useState(6000);const[mode,setMode]=useState("standard");const[message,setMessage]=useState("");
 useEffect(()=>{if(!user)return;let unsub:(()=>void)|undefined;getDoc(doc(db,"users",user.uid)).then(async userSnap=>{const id=userSnap.data()?.activeOrganizationId;if(!id)return;const orgSnap=await getDoc(doc(db,"organizations",id));setOrg(orgSnap.exists()?{id,...orgSnap.data()} as Org:null);unsub=onSnapshot(query(collection(db,"organizations",id,"employees"),orderBy("createdAt","asc")),snap=>setEmployees(snap.docs.map(d=>({id:d.id,...d.data()} as Employee))))});return()=>unsub?.()},[user]);
 const activeCount=useMemo(()=>employees.filter(e=>e.active!==false).length,[employees]);const canAdd=!!org&&(org.employeeLimit||0)>activeCount;
 async function add(){if(!org||!name.trim())return;if(!canAdd){setMessage(ro?"Ai atins limita planului. Fă upgrade sau arhivează un angajat.":"You reached the plan limit. Upgrade or archive an employee.");return;}await addDoc(collection(db,"organizations",org.id,"employees"),{displayName:name.trim(),employeeCode:code.trim()||null,department:department.trim()||null,grossSalary:gross,workMode:mode,active:true,createdAt:serverTimestamp(),updatedAt:serverTimestamp()});await updateDoc(doc(db,"organizations",org.id),{activeEmployees:activeCount+1,updatedAt:serverTimestamp()});setName("");setCode("");setMessage("")}
 async function toggle(employee:Employee){if(!org)return;const activate=employee.active===false;if(activate&&activeCount>=(org.employeeLimit||0)){setMessage(ro?"Nu poți reactiva angajatul fără loc disponibil.":"You cannot reactivate this employee without an available seat.");return;}await updateDoc(doc(db,"organizations",org.id,"employees",employee.id),{active:activate,updatedAt:serverTimestamp()});await updateDoc(doc(db,"organizations",org.id),{activeEmployees:activeCount+(activate?1:-1),updatedAt:serverTimestamp()})}
 if(loading)return <main className="platform-page">...</main>;if(!user||!org)return <main className="platform-page"><WorkspaceTabs/><section className="platform-hero"><h1 className="platform-title">{ro?"Creează mai întâi compania și alege un plan Business.":"Create a company and choose a Business plan first."}</h1></section></main>;
 return <main className="platform-page"><WorkspaceTabs/><section className="platform-hero"><span className="platform-kicker">{org.name}</span><h1 className="platform-title">{ro?"Angajați și istoric salarial separat.":"Employees with separate payroll history."}</h1><p className="platform-subtitle">{activeCount} / {org.employeeLimit||0} {ro?"angajați activi. Angajații arhivați nu ocupă loc și își păstrează lunile, documentele și auditul.":"active employees. Archived employees do not use a seat and keep their months, documents and audit trail."}</p></section>{message&&<div style={{marginTop:16,padding:14,border:"1px solid rgba(245,158,11,.3)",borderRadius:14,color:"#fbbf24"}}>{message}</div>}<section className="platform-grid"><article className="platform-card span-4"><h2>{ro?"Adaugă angajat":"Add employee"}</h2><div style={{display:"grid",gap:11}}><input className="auth-input" placeholder={ro?"Nume sau identificator":"Name or identifier"} value={name} onChange={e=>setName(e.target.value)}/><input className="auth-input" placeholder={ro?"Cod intern angajat":"Internal employee code"} value={code} onChange={e=>setCode(e.target.value)}/><input className="auth-input" placeholder={ro?"Departament":"Department"} value={department} onChange={e=>setDepartment(e.target.value)}/><input className="auth-input" type="number" value={gross} onChange={e=>setGross(Number(e.target.value))}/><select className="auth-input" value={mode} onChange={e=>setMode(e.target.value)}><option value="standard">{ro?"Program normal":"Standard schedule"}</option><option value="parttime">Part-time</option><option value="shifts">{ro?"Ture":"Shifts"}</option><option value="custom">{ro?"Personalizat":"Custom"}</option></select><button className="platform-button" disabled={!canAdd} onClick={add}>{canAdd?(ro?"Adaugă angajat":"Add employee"):(ro?"Limită atinsă":"Limit reached")}</button></div></article><article className="platform-card span-8"><h2>{ro?"Lista angajaților":"Employee list"}</h2><div style={{display:"grid",gap:9}}>{employees.map(employee=><div key={employee.id} style={{display:"grid",gridTemplateColumns:"1fr auto",gap:12,alignItems:"center",padding:14,border:"1px solid var(--line-ui)",borderRadius:16,background:"var(--surface-raised)",opacity:employee.active===false?.62:1}}><div><strong>{employee.displayName}</strong><div style={{marginTop:4,color:"var(--text-muted)",fontSize:11}}>{employee.employeeCode||"—"} · {employee.department||"—"} · {employee.grossSalary?.toFixed(2)} lei · {employee.workMode}</div></div><button className="platform-button secondary" onClick={()=>toggle(employee)}>{employee.active===false?(ro?"Reactivează":"Reactivate"):(ro?"Arhivează":"Archive")}</button></div>)}{employees.length===0&&<p>{ro?"Nu există încă angajați.":"No employees yet."}</p>}</div></article></section></main>}
