"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { onAuthStateChanged, type User } from "firebase/auth";
import { auth } from "@/lib/firebase";
import { useUI } from "@/lib/ui-context";
import { getSecureHeaders } from "@/lib/secure-api";
import { PLANS, type PlanDefinition } from "@/lib/plans";
import styles from "./pricing.module.css";

function money(value: number, language: "ro"|"en") { return new Intl.NumberFormat(language === "ro" ? "ro-RO" : "en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 }).format(value) + " lei"; }

export default function PricingPage() {
  const { language } = useUI(); const ro = language === "ro";
  const [billing,setBilling]=useState<"month"|"year">("month");
  const [user,setUser]=useState<User|null>(null); const [loading,setLoading]=useState<string|null>(null); const [error,setError]=useState("");
  useEffect(()=>onAuthStateChanged(auth,setUser),[]);
  const creditPlans=useMemo(()=>PLANS.filter(p=>p.kind==="credit_pack"),[]);
  const personal=PLANS.find(p=>p.id===`personal_${billing === "month" ? "monthly" : "yearly"}`)!;
  const business=useMemo(()=>["starter","growth","pro","plus"].map(name=>PLANS.find(p=>p.id===`business_${name}_${billing === "month" ? "monthly" : "yearly"}`)!).filter(Boolean),[billing]);

  async function checkout(plan:PlanDefinition){
    if(!user){window.location.href="/login?next=/pricing";return;}
    setError("");setLoading(plan.id);
    try{const headers=await getSecureHeaders();const res=await fetch("/api/create-checkout-session",{method:"POST",headers,body:JSON.stringify({planId:plan.id,email:user.email})});const data=await res.json();if(!res.ok||!data.url)throw new Error(data.error||"CHECKOUT_FAILED");window.location.href=data.url;}catch(e){setError(e instanceof Error?e.message:"CHECKOUT_FAILED");}finally{setLoading(null)}
  }

  const personalFeatures=ro?["Maximum 3 profiluri salariale","Calcule lunare nelimitate","Istoric, comparații, PDF și Excel","Asistent AI inclus în limita planului","Creditele cumpărate anterior rămân în cont"]:["Up to 3 payroll profiles","Unlimited monthly calculations","History, comparisons, PDF and Excel","AI assistant included within plan limits","Previously purchased credits stay in your account"];
  const businessFeatures=(plan:PlanDefinition)=>ro?[`${plan.employeeLimit} angajați activi`,`${plan.adminLimit} conturi administrative`,"Profil, calendar și istoric pentru fiecare angajat","Ture, reguli, bonusuri și taxe configurabile","Upgrade în același spațiu, fără pierderea datelor"]:[`${plan.employeeLimit} active employees`,`${plan.adminLimit} administrative accounts`,"Profile, calendar and history for every employee","Configurable shifts, rules, bonuses and taxes","Upgrade in the same workspace without losing data"];

  return <main className={styles.page}>
    <section className={styles.hero}><span className="platform-kicker">{ro?"Pachete și abonamente":"Packs and subscriptions"}</span><h1>{ro?"Plătești doar pentru modul în care folosești platforma.":"Pay only for the way you use the platform."}</h1><p>{ro?"Calculatorul brut-net simplu rămâne gratuit. Pentru calculul lunar complet folosești credite care nu expiră sau un abonament Personal ori Business, cu upgrade în același cont.":"The basic gross-net calculator remains free. Use non-expiring credits or a Personal or Business subscription for complete monthly calculations, with in-place upgrades."}</p><div className={styles.switch}><button className={billing==="month"?styles.active:""} onClick={()=>setBilling("month")}>{ro?"Lunar":"Monthly"}</button><button className={billing==="year"?styles.active:""} onClick={()=>setBilling("year")}>{ro?"Anual – 2 luni incluse":"Yearly – 2 months included"}</button></div></section>
    {error&&<div className={styles.error}>{error}</div>}

    <section className={styles.section}><div className={styles.sectionHead}><div><span className="platform-kicker">{ro?"Fără abonament":"No subscription"}</span><h2>{ro?"Pachete de calcule":"Calculation packs"}</h2></div><p>{ro?"Un credit deblochează o lună pentru un profil. Corectările și recalculările aceleiași luni nu mai consumă alt credit.":"One credit unlocks one month for one profile. Corrections and recalculations for the same month do not consume another credit."}</p></div><div className={styles.grid}>{creditPlans.map(plan=><PlanCard key={plan.id} plan={plan} language={language} features={ro?["Creditele nu expiră","Luna deblocată rămâne în istoric","Toate setările de program și sporuri"]:["Credits do not expire","Unlocked month stays in history","All schedule and bonus settings"]} loading={loading===plan.id} onClick={()=>checkout(plan)} />)}</div></section>

    <section className={styles.section}><div className={styles.sectionHead}><div><span className="platform-kicker">Personal</span><h2>Premium Personal</h2></div><p>{ro?"Pentru persoane care fac simulări frecvente, păstrează mai multe profiluri și vor toate instrumentele într-un singur plan.":"For people who run frequent simulations, keep multiple profiles and want all personal tools in one plan."}</p></div><div className={styles.grid}><PlanCard plan={personal} language={language} features={personalFeatures} loading={loading===personal.id} onClick={()=>checkout(personal)} /><div className={`${styles.card} ${styles.featured}`} style={{gridColumn:"span 2"}}><span className={styles.tag}>{ro?"Configurare gratuită":"Free setup"}</span><h3>{ro?"Construiești calendarul înainte să plătești":"Build the calendar before paying"}</h3><p className={styles.muted}>{ro?"Poți configura programul, turele, sporurile și zilele speciale. Valorile complete — net, taxe, beneficii și cost angajator — rămân protejate până la deblocarea lunii.":"Configure schedules, shifts, bonuses and special days. Complete values — net pay, taxes, benefits and employer cost — stay protected until the month is unlocked."}</p><ul className={styles.features}>{(ro?["Calculatorul brut-net simplu rămâne gratuit","1 credit deblochează o lună pentru un profil","Recalculările lunii deblocate nu mai consumă credit"]:["The basic gross-net calculator remains free","1 credit unlocks one month for one profile","Recalculating an unlocked month uses no additional credit"]).map(x=><li key={x}>{x}</li>)}</ul><Link href={user?"/calculator-universal":"/register"} className={`${styles.button} ${styles.secondary}`} style={{display:"flex",alignItems:"center",justifyContent:"center"}}>{ro?"Configurează o lună":"Configure a month"}</Link></div></div></section>

    <section className={styles.section}><div className={styles.sectionHead}><div><span className="platform-kicker">Business</span><h2>{ro?"Planuri pentru firme":"Plans for companies"}</h2></div><p>{ro?"Numărul de angajați activi și conturile administrative sunt limite separate. Angajații arhivați nu ocupă loc, iar istoricul lor rămâne disponibil.":"Active employees and administrative accounts are separate limits. Archived employees do not use a seat, while their history remains available."}</p></div><div className={`${styles.grid} ${styles.businessGrid}`}>{business.map(plan=><PlanCard key={plan.id} plan={plan} language={language} features={businessFeatures(plan)} loading={loading===plan.id} onClick={()=>checkout(plan)} />)}</div><div className={styles.notice}>{ro?"Depășirea limitei: firma poate cumpăra extensii de +5 angajați la 29,99 lei/lună (maximum două extensii pe Starter/Growth) sau poate face upgrade. Nu este nevoie de alt cont și nu se mută datele.":"Going over the limit: the company can buy +5 employee add-ons for 29.99 lei/month (up to two add-ons on Starter/Growth) or upgrade. No second account or data migration is required."}</div></section>

    <section className={`${styles.section} ${styles.card} ${styles.enterprise}`}><div><span className="platform-kicker">Enterprise</span><h2>{ro?"Peste 100 de angajați sau cerințe speciale":"More than 100 employees or custom requirements"}</h2><p className={styles.muted}>{ro?"Oferta se calculează după numărul de angajați și firme/CUI, administratori, stocare, volum AI, SSO, migrare, integrări și nivelul de suport. Prețul pornește de la 699,99 lei/lună.":"The quote depends on employees and legal entities, administrators, storage, AI volume, SSO, migration, integrations and support level. Pricing starts at 699.99 lei/month."}</p></div><div><div className={styles.price}>{ro?"de la ":"from "}{money(699.99,language)}</div><Link className={styles.button} href="/contact" style={{display:"flex",alignItems:"center",justifyContent:"center",marginTop:18}}>{ro?"Solicită ofertă":"Request a quote"}</Link></div></section>
  </main>;
}

function PlanCard({plan,language,features,loading,onClick}:{plan:PlanDefinition;language:"ro"|"en";features:string[];loading:boolean;onClick:()=>void}){const ro=language==="ro";return <article className={`${styles.card} ${plan.highlighted?styles.featured:""}`}>{plan.highlighted&&<span className={styles.tag}>{ro?"Recomandat":"Recommended"}</span>}<h3>{ro?plan.nameRo:plan.nameEn}</h3><div className={styles.muted}>{plan.kind==="credit_pack"?(ro?"Plată unică":"One-time payment"):(plan.interval==="year"?(ro?"Facturare anuală":"Yearly billing"):(ro?"Facturare lunară":"Monthly billing"))}</div><div className={styles.price}>{money(plan.priceLei||0,language)}</div><div className={styles.interval}>{plan.interval==="month"?`/ ${ro?"lună":"month"}`:plan.interval==="year"?`/ ${ro?"an":"year"}`:""}</div><ul className={styles.features}>{features.map(x=><li key={x}>{x}</li>)}</ul><button className={styles.button} disabled={loading} onClick={onClick}>{loading?(ro?"Se deschide plata...":"Opening checkout..."):(ro?"Alege planul":"Choose plan")}</button></article>}
