"use client";
import Link from "next/link";
import { useEffect,useState } from "react";
import { doc,getDoc } from "firebase/firestore";
import WorkspaceTabs from "@/components/WorkspaceTabs";
import { useUI } from "@/lib/ui-context";
import { useCurrentUser } from "@/lib/use-current-user";
import { db } from "@/lib/firebase";

type Account={plan?:string;credits?:number;freeCalculationUsed?:boolean;employeeLimit?:number;adminLimit?:number;subscriptionStatus?:string;activeOrganizationId?:string};
export default function Dashboard(){const{language}=useUI();const ro=language==="ro";const{user,loading}=useCurrentUser();const[account,setAccount]=useState<Account|null>(null);useEffect(()=>{if(!user)return;getDoc(doc(db,"users",user.uid)).then(s=>setAccount(s.exists()?s.data() as Account:{}))},[user]);if(loading)return <main className="platform-page">...</main>;if(!user)return <main className="platform-page"><section className="platform-hero"><h1 className="platform-title">{ro?"Intră în cont pentru panoul personal.":"Sign in to open your dashboard."}</h1><Link className="platform-button" href="/login">{ro?"Autentificare":"Sign in"}</Link></section></main>;
 const cards=[
  {title:ro?"Calcul nou":"New calculation",text:ro?"Alege program normal, part-time, ture sau personalizat.":"Choose standard, part-time, shifts or a custom schedule.",href:"/calculator-universal",cta:ro?"Deschide calculatorul":"Open calculator"},
  {title:ro?"Profiluri salariale":"Payroll profiles",text:ro?"Salvează până la 3 profiluri personale în Premium.":"Save up to 3 personal profiles with Premium.",href:"/profiles",cta:ro?"Gestionează profiluri":"Manage profiles"},
  {title:ro?"Spațiu pentru firmă":"Company workspace",text:ro?"Angajați, reguli comune, roluri și istoric.":"Employees, shared rules, roles and history.",href:"/company",cta:ro?"Deschide compania":"Open company"},
  {title:ro?"Asistent AI":"AI Assistant",text:ro?"Descrie programul și primești o configurare de confirmat.":"Describe your schedule and receive a configuration to confirm.",href:"/assistant",cta:ro?"Întreabă asistentul":"Ask assistant"},
 ];
 return <main className="platform-page"><WorkspaceTabs/><section className="platform-hero"><span className="platform-kicker">{ro?"Panou personal":"Personal dashboard"}</span><h1 className="platform-title">{ro?`Bine ai revenit${user.displayName?`, ${user.displayName}`:""}.`:`Welcome back${user.displayName?`, ${user.displayName}`:""}.`}</h1><p className="platform-subtitle">{ro?"De aici intri în calculator, profiluri, companie, securitate și plăți. Datele lunilor salvate rămân separate de setările curente.":"Open the calculator, profiles, company, security and billing from here. Saved months remain separate from current settings."}</p></section><section className="platform-grid"><article className="platform-card span-4"><span className="platform-kicker">Plan</span><h2>{account?.plan||"free"}</h2><p>{ro?"Abonamentul și creditele sunt actualizate automat de Stripe.":"Subscriptions and credits are updated automatically by Stripe."}</p><Link className="platform-button secondary" href="/pricing">{ro?"Vezi planurile":"View plans"}</Link></article><article className="platform-card span-4"><span className="platform-kicker">{ro?"Credite":"Credits"}</span><h2>{account?.credits||0}</h2><p>{ro?"Un credit deblochează o lună pentru un profil. Lunile deja deblocate pot fi recalculate fără alt credit.":"One credit unlocks one month for one profile. Already unlocked months can be recalculated without another credit."}</p></article><article className="platform-card span-4"><span className="platform-kicker">Business</span><h2>{account?.employeeLimit||0} / {account?.adminLimit||0}</h2><p>{ro?"Limită angajați activi / conturi administrative, după plan.":"Active employee / administrative account limit under your plan."}</p></article>{cards.map(card=><article className="platform-card span-6" key={card.href}><h2>{card.title}</h2><p>{card.text}</p><Link className="platform-button" href={card.href}>{card.cta}</Link></article>)}</section></main>}
